[package]
name = "serde-json-tokenizer-deserialize-bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hf-hub = "0.3.2"
serde_json = "1.0.117"
tokenizers = "0.19.1"
